import Database from "better-sqlite3";
import fs from "fs";
import path from "path";
import {
  COLUMN_GLOSSARY,
  getGlossaryEntry,
  getTableNote,
  type GlossaryEntry,
} from "../lib/column-glossary";

const root = process.cwd();
const dbPath = path.join(root, "perseus_equipment_database.db");

if (!fs.existsSync(dbPath)) {
  console.error("Missing perseus_equipment_database.db at project root.");
  process.exit(1);
}

const db = new Database(dbPath, { readonly: true, fileMustExist: true });
const tables = db
  .prepare(
    "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name",
  )
  .all() as { name: string }[];

/**
 * Tables that are big enough to make `SELECT DISTINCT` per column expensive.
 * For these we cap the sample-value detection at a smaller probe so the dump
 * stays fast.
 */
const SAMPLE_THRESHOLD = 50;
const SAMPLE_PROBE_LIMIT = 200;
const SAMPLE_RENDER_LIMIT = 12;

/**
 * Pull up to SAMPLE_PROBE_LIMIT distinct values from a TEXT column. Returns
 * `null` if there are more than SAMPLE_THRESHOLD distinct values (column is
 * not low-cardinality and inlining would be noise) or if probing fails.
 */
function probeDistinct(table: string, column: string): string[] | null {
  try {
    const rows = db
      .prepare(
        `SELECT DISTINCT "${column.replace(/"/g, '""')}" AS v
         FROM "${table.replace(/"/g, '""')}"
         WHERE "${column.replace(/"/g, '""')}" IS NOT NULL
         LIMIT ${SAMPLE_PROBE_LIMIT}`,
      )
      .all() as { v: unknown }[];
    if (rows.length > SAMPLE_THRESHOLD) return null;
    const values = rows
      .map((r) => (typeof r.v === "string" ? r.v : String(r.v ?? "")))
      .map((s) => s.trim())
      .filter((s) => s.length > 0 && s.length <= 40);
    if (values.length === 0) return null;
    const unique = Array.from(new Set(values));
    return unique.slice(0, SAMPLE_RENDER_LIMIT);
  } catch {
    return null;
  }
}

function renderEntry(
  entry: GlossaryEntry | undefined,
  probed: string[] | null,
): string {
  const parts: string[] = [];
  if (entry?.description) {
    parts.push(entry.description);
  }
  if (entry?.aliases?.length) {
    parts.push(`aliases: ${entry.aliases.join(", ")}`);
  }
  const sample = entry?.sampleValues ?? probed;
  if (sample && sample.length > 0) {
    parts.push(`values: ${sample.join(", ")}`);
  }
  return parts.length > 0 ? ` — ${parts.join(" · ")}` : "";
}

let md =
  "# Generated schema (do not edit by hand)\n\nRun `npm run dump-schema` after schema changes. Annotations come from `lib/column-glossary.ts`; sample values are inlined for low-cardinality TEXT columns.\n\n";

for (const { name } of tables) {
  md += `## ${name}\n\n`;
  const tableNote = getTableNote(name);
  if (tableNote?.description) {
    md += `_${tableNote.description}_\n\n`;
  }
  const cols = db.prepare(`PRAGMA table_info("${name.replace(/"/g, '""')}")`).all() as {
    name: string;
    type: string;
    notnull: number;
    pk: number;
  }[];
  for (const c of cols) {
    const flags = [c.pk ? "PK" : "", c.notnull ? "NOT NULL" : ""].filter(Boolean).join(", ");
    const entry = getGlossaryEntry(name, c.name);
    /**
     * Only probe TEXT columns that don't already have curated sample values
     * and that aren't obviously high-cardinality (names, free text). The
     * probe itself short-circuits at SAMPLE_THRESHOLD, but skipping the
     * common high-cardinality columns keeps the dump fast on big tables.
     */
    const skipProbe =
      c.type.toUpperCase() !== "TEXT" ||
      Boolean(entry?.sampleValues) ||
      /name|description|email|phone|address|comment|note|displaytext|jurisdictiondisplaytext/i.test(
        c.name,
      );
    const probed = skipProbe ? null : probeDistinct(name, c.name);
    const annotation = renderEntry(entry, probed);
    md += `- **${c.name}** (${c.type})${flags ? ` _${flags}_` : ""}${annotation}\n`;
  }
  md += "\n";
}

db.close();

const outPath = path.join(root, "lib", "generated-schema.md");
fs.writeFileSync(outPath, md, "utf8");

const tsPath = path.join(root, "lib", "generated-schema.ts");
fs.writeFileSync(
  tsPath,
  "/** Auto-generated by npm run dump-schema. */\nexport const GENERATED_SCHEMA_TEXT: string = " +
    JSON.stringify(md) +
    ";\n",
  "utf8",
);

const glossarySize = Object.keys(COLUMN_GLOSSARY).length;
console.log(
  `Wrote ${outPath} and ${tsPath} (${tables.length} tables, ${glossarySize} glossary entries merged).`,
);
